services:
  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
